version: "3.8"

services:    
  db:
    build: ./maria_db/.
    container_name: maria-cont
    env_file:
      - .env
    service_name: db
    restart: always
    networks:
      - app-network
    volumes:
      - DataBase:/var/lib/mysql/

  wordpress:
    depends_on:
       - db
    build:
      context: ./wp-php-fpm/.
    container_name: wordpress-cont
    env_file:
      - .env
    service_name: wordpress
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx/.
    container_name: nginx-cont
    service_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - app-network

volumes:
  Wordpress:
    name : wordpress
  DataBase:
    name : mariadb
networks:
  app-network:
    name : app-web