version: "3.8"

services:    
  db:
    env_file:
      - .env
    build: ./mariadb/.
    container_name: maria-cont
    image: mariadb:mytag
    restart: always
    networks:
      - app-network
    volumes:
      - DataBase:/var/lib/mysql/

  wordpress:
    depends_on:
       - db
    env_file:
      - .env
    build:
      context: ./wordpress/.
    container_name: wordpress-cont
    image: wordpress:mytag
    restart: always
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx/.
    container_name: nginx-cont
    image: nginx:mytag
    ports:
      - "443:443"
    restart: always
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - app-network

volumes:
  Wordpress:
    name : wordpress
  DataBase:
    name : mariadb
networks:
  app-network:
    name: web-network