CREATE DATABASE $MYSQL_DATABASE;

CREATE USER '$MYSQL_USER'@'$MYSQL_HOST' identified by '$MYSQL_PASSWORD';

GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO ''$MYSQL_USER''@'localhost';

FLUSH PRIVILEGES;
